# Generated by Django 4.1.5 on 2023-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pang", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smallcategory",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
