# Generated by Django 4.2.1 on 2023-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pang", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="name",
        ),
        migrations.AddField(
            model_name="item",
            name="contents",
            field=models.CharField(default="", max_length=200),
        ),
    ]
