# Generated by Django 4.1.5 on 2023-06-04 12:50

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pang", "0002_category_order_item_order_smallcategory_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AlterField(
            model_name="item",
            name="order",
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AlterField(
            model_name="smallcategory",
            name="order",
            field=positions.fields.PositionField(default=-1),
        ),
    ]
