# Generated by Django 4.1.5 on 2023-06-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pang", "0003_alter_category_order_alter_item_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="order",
        ),
        migrations.RemoveField(
            model_name="item",
            name="order",
        ),
        migrations.RemoveField(
            model_name="smallcategory",
            name="order",
        ),
    ]
