# Generated by Django 4.1.5 on 2023-06-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pang", "0003_alter_item_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="big_category",
        ),
        migrations.CreateModel(
            name="SmallCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                (
                    "parent_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small",
                        to="pang.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="small_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pang.smallcategory",
            ),
        ),
    ]
